/* -------------------------------------------------------------------------- */
/*                               Define DB Model                              */
/* -------------------------------------------------------------------------- */

   /*
      Note that _id field is included by default within each document
      once it is generated by mongoose into mongo db even though this
      is not represented within the schema defined belo
      
      In addition, a _V for version field is added any time a new doc
      is created outside the seeds file. 
    */

/* --------------------------- Import Dependencies -------------------------- */

  const mongoose = require("mongoose");
  const Schema = mongoose.Schema;

/* ----------------------------- Define Schemas ----------------------------- */

  // Define Schema (representing document objects stored on the mongo db)
  const transactionSchema = new Schema(
    {
      name: {
        type: String,
        trim: true,
        required: "Enter a name for transaction" // This will display if a user tries to submit with no name
      },
      value: {
        type: Number,
        required: "Enter an amount" // This will display if a user tries to submit with no value
      },
      date: {
        type: Date,
        default: Date.now // This will be the default date generated for the transaction
      }
    }
  );

  // Convert schema into a mongoose model (arg 1 is name of model arg 2 is what schema you want model to have)
  const Transaction = mongoose.model("Transaction", transactionSchema);

/* ------------------------------ Export Model ------------------------------ */

  module.exports = Transaction;
